version: "3.9"

networks:
  db:

services:

  django:
     build: ./myproj
     command: sh -c "python manage.py runserver 0.0.0.0:8000"
     ports:
        - "8000:8000"
     restart: always
     networks:
       - db

  nginx:
     build:
       context: ./nginx
     ports:
       - "8080:80"
     restart: always
     environment:
       - NGINX_PORT=80
     depends_on:
       - django
     networks:
      - db

  postgres:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    networks:
      - db